# Numpy Handson

**Revision**

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Dimentions

In [ ]:
arr=np.array([1,2,3]) #1d
print(arr.ndim)
arr=np.array([[1,2,3],[4,5,6]]) # 2d
print(arr.ndim)
arr=np.array([[[[1,2,3],[4,5,6]],[[10,11,12],[14,15,16]]]]) # 4d
print(arr.ndim)

1
2
4


In [ ]:
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)

[[[[[1 2 3 4 5]]]]]


In [ ]:
arr=np.array([1,2,3])
print(arr.shape)
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(3,)
(2, 3)


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.size)
arr=np.array([1,2,3])
print(arr.size)

6
3


In [ ]:
np.zeros(5)

np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones(5)
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(2,3)
np.eye(4,7)
# np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.]])

In [ ]:
#Range
# arange

arr=np.arange(1,10) # start to end-1, 1 to 9

print(arr)

arr=np.arange(5)
print(arr)

arr=np.arange(10,51,10) #10, 20,30,40,50
arr

[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


array([10, 20, 30, 40, 50])

In [ ]:
arr=np.linspace(1,10,4)
print(arr)

[ 1.  4.  7. 10.]


In [ ]:
2,9,2

In [ ]:
arr=np.array([1,2,3,4])
print(arr.dtype)
arr=np.array(["a","b","c"])
print(arr.dtype)
arr=np.array([10.5,6.7])
print(arr.dtype)

int64
<U1
float64


In [ ]:
arr=np.array([5.5,6.6,7.89,10.5],dtype='int')
print(arr)
arr=np.array([10,20,30],dtype='float')
print(arr)

[ 5  6  7 10]
[10. 20. 30.]


In [ ]:
arr=np.array([10.5888,6.79999])
rounded=np.round(arr,2)
print(rounded)
print(arr.astype('int'))

print(arr)

[10.59  6.8 ]
[10  6]
[10.5888   6.79999]


In [ ]:
#copy view
arr=np.array([1,2,3,4])
# c=np.copy(arr)
c=arr.copy()
print(c)
c[0]=9
print(c)
print(arr)

[1 2 3 4]
[9 2 3 4]
[1 2 3 4]


In [ ]:
arr=np.array([1,2,3,4])

v=arr.view()
v[0]=9
print(v)

print(arr)

[9 2 3 4]
[9 2 3 4]


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9])
newarr=arr.reshape(3,3) # [[1,2,3],[],[]]
print(newarr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.reshape(3,4))
print(arr.reshape(2,6))
print()
print(arr.reshape(2,3,2))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
arr=np.array([1,2,3,4,5,6,7])
print(arr.reshape(1,1,1,7))

[[[[1 2 3 4 5 6 7]]]]


In [ ]:
arr=np.array([1,2,3,4,5,6,7])
#             0 1 2 3 4 5 6

print(arr[3])
print(arr[1:6])


4
[2 3 4 5 6]


In [ ]:
#               0        1
arr=np.array([[1,2,3],[4,5,6]])
#              0 1 2   0 1 2

print(arr[1,0])
print(arr[1,1:3])
print(arr[0:2,1:3])



4
[5 6]
[[2 3]
 [5 6]]


1) Create three arrays (1,2,3,4,5)

first data type integer, second float, third string

In [ ]:
#int
arr=np.array([1,2,3,4,5],dtype='int')
brr=np.array([1,2,3,4,5],dtype='float')
crr=np.array([1,2,3,4,5],dtype='str')

print(arr)
print(brr)
print(crr)


[1 2 3 4 5]
[1. 2. 3. 4. 5.]
['1' '2' '3' '4' '5']


2) Create numpy arrays with 0 dimention, 1 dim, 2 dim, 3 dim.
  - Print their shape and number of dimentions
  

In [ ]:
#0
arr=np.array(10)
print(arr.ndim)
print(arr.shape)

0
()


In [ ]:
#1
arr=np.array([1,2,3,3,4,5])
print(arr.ndim)
print(arr.shape)

1
(6,)


In [ ]:
arr=np.array([[1,2],[3,4],[5,6]])
print(arr.ndim)
print(arr.shape)

2
(3, 2)


In [ ]:
arr=np.array([ [ [1,2],[3,4],[5,6]], [[7,8],[9,10],[11,12]] ])
print(arr.ndim)
print(arr.shape)

3
(2, 3, 2)


3) Create identity matrix of 2 x 2, 3 x 3, 4 x 5, 10 x 6

Use identity and eye

In [ ]:
m = np.identity(2)
print(m)

[[1. 0.]
 [0. 1.]]


In [ ]:
m = np.identity(3)
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [ ]:
np.eye(10,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

3) Using arange, create a 1d,2d,3d array.

Use arange and reshape -> rehape (a,b) is 2d. reshape(a,b,c) is 3d

In [ ]:
arr=np.arange(1,21)
print(arr) #1d

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
print(arr.reshape(5,4)) #2d

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [ ]:
print(arr.reshape(2,5,2)) # 3d

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


4) create a array of 5 x 4 .

a) filled with zeros

 b) filled with ones

 c) filled with 7

In [ ]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.full((5,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
np.random.random(10)

array([0.67924264, 0.06959292, 0.85140285, 0.49132135, 0.42030641,
       0.88353517, 0.08002734, 0.22348044, 0.21852804, 0.90760408])

5) Create a 1d array of 10 random numbers between 10 to 100

use random.randint

In [ ]:
np.random.randint(10,100,10)


array([99, 74, 38, 11, 25, 22, 69, 22, 79, 41])

6) Create an 1d array looking like this -> 5,10,15,20.......105



In [ ]:
np.arange(5,106,5)

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100, 105])

7) Using indexing access the elements listed.

a) [[1,2,3],[4,5,6],[7,8,9]]

-> 8

-> 7 8 9

-> 5 6

-> 2 3 5 6 8 9

b)

In [ ]:
#                0       1      2
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
#              0 1 2   0 1 2   0 1 2

print(arr[2,1])
print(arr[2])
print(arr[1,1:])
print(arr[0:3,1:].flatten())

8
[7 8 9]
[5 6]
[2 3 5 6 8 9]


8) Create a numpy array. And find.

a) max

b) min

c) sum

d) mean


In [ ]:
arr = np.array([23, 45, 12, 67, 34, 89, 56, 78, 90, 11])
print(np.max(arr))
print(np.min(arr))
print(np.sum(arr))
print(np.mean(arr))

90
11
505
50.5


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print("Max value:", arr.max())
print("Min value :", arr.min())
print("Sum of the numbers:", arr.sum())
print("Mean Value :", arr.mean())

Max value: 5
Min value : 1
Sum of the numbers: 15
Mean Value : 3.0


9) Create a array of numbers, and filter out all the numbers which are greater than the avg of the array.


 Don't use for loop for filter.



In [ ]:
arr = np.array([10, 25, 30, 5, 40, 15, 35, 20, 45, 8])
avg=arr.mean()
print("Avg=",avg)

ans=arr[arr>avg]
print(ans)

Avg= 23.3
[25 30 40 35 45]


10. Creat an array of nuumber, filter out all the even numbers.

In [ ]:
arr = np.array([10, 25, 30, 5, 40, 15, 35, 20, 45, 8])

ans=arr[arr % 2 ==0]

print(ans)

[10 30 40 20  8]


11) Create two arrays , add, subtract, multiply and devide them

In [ ]:
arr=np.array([3,4,7,9,22,4,6,8])

arr1=np.array([3,4,7,9,22,4,6,5])

print(arr + arr1)
print(arr - arr1)
print(arr * arr1)
print(arr / arr1)

[ 6  8 14 18 44  8 12 13]
[0 0 0 0 0 0 0 3]
[  9  16  49  81 484  16  36  40]
[1.  1.  1.  1.  1.  1.  1.  1.6]


12) Create a random array of 50 elements between 1, 100

a) print the first 10 elements

b) print last 10 elements using positive index

c) print the last 10 using negative indexing

d) print the whole array using index

e) print the alternate element ( [1,2,3,4,5]-> 1 3 5)

d) print the reverse of the array

In [ ]:
arr=np.random.randint(1,100,50)
print(arr)

[39 34 77 68 24 85  5 54 64 39 22 84 41 72 79 20 40  1 46 19 31 91  1 70
 16 85 23 27 39 35 81 97 97 54 41 85  3 81  2  9 77  1 40 61 85 21 57 49
 40 94]


In [ ]:
#a)
print(arr[:10])

[39 34 77 68 24 85  5 54 64 39]


In [ ]:
#b)
print(arr[40:])

n=len(arr)
print(n)

print(arr[n-10:])

[77  1 40 61 85 21 57 49 40 94]
50
[77  1 40 61 85 21 57 49 40 94]


In [ ]:
# c)
print(arr[-10:])

[77  1 40 61 85 21 57 49 40 94]


In [ ]:
#d)
print(arr[:])

[39 34 77 68 24 85  5 54 64 39 22 84 41 72 79 20 40  1 46 19 31 91  1 70
 16 85 23 27 39 35 81 97 97 54 41 85  3 81  2  9 77  1 40 61 85 21 57 49
 40 94]


In [ ]:
#e)
print(arr[::2])

[39 77 24  5 64 22 41 79 40 46 31  1 16 23 39 81 97 41  3  2 77 40 85 57
 40]


In [ ]:
print(arr[::-1])

[94 40 49 57 21 85 61 40  1 77  9  2 81  3 85 41 54 97 97 81 35 39 27 23
 85 16 70  1 91 31 19 46  1 40 20 79 72 41 84 22 39 64 54  5 85 24 68 77
 34 39]
