# Good Morning Everyone!!! We will wait for everyone to join and will start at 10:08 AM

In [ ]:
# Matrix
# Matrix operations
# Transpose of a Matrix
# Detarminant of a Matrix
# Inverse of a Matrix
# Rank of a Matrix
# Eigen values and Eigen vectors

In [ ]:
# Create a 3x3 matrix (3 Rows, 3 Cols). Perform the following operations ->
# a. Add 50 to your matrix
# b. Subtract 20 from your matrix
# c. Multiply 3 in your matrix
# d. Devide your matrix by 4

# time -> 10:23

In [ ]:
import numpy as np

In [ ]:
M1 = np.random.randint(10,50,size=(3,3))
M1

array([[15, 10, 30],
       [43, 40, 42],
       [27, 30, 11]])

In [ ]:
# a)
M1+50

array([[65, 60, 80],
       [93, 90, 92],
       [77, 80, 61]])

In [ ]:
# b)
M1-20

array([[ -5, -10,  10],
       [ 23,  20,  22],
       [  7,  10,  -9]])

In [ ]:
# c)
M1*3

array([[ 45,  30,  90],
       [129, 120, 126],
       [ 81,  90,  33]])

In [ ]:
# d)
M1/4

array([[ 3.75,  2.5 ,  7.5 ],
       [10.75, 10.  , 10.5 ],
       [ 6.75,  7.5 ,  2.75]])

In [ ]:
# Create two 3x3 matrix
# addition, subtraction, multiplication, division between two matrix

# time -> 10:38

In [ ]:
M1 = np.random.randint(20,40, size=(3,3))
M2 = np.random.randint(50,70, size=(3,3))

In [ ]:
M1

array([[21, 30, 31],
       [37, 30, 37],
       [25, 22, 22]])

In [ ]:
M2

array([[59, 67, 68],
       [60, 69, 57],
       [63, 54, 56]])

In [ ]:
# Addition
M1+M2

array([[80, 97, 99],
       [97, 99, 94],
       [88, 76, 78]])

In [ ]:
# Sub.
M1-M2

array([[-38, -37, -37],
       [-23, -39, -20],
       [-38, -32, -34]])

In [ ]:
# Mul.
M1@M2

array([[4992, 5151, 4874],
       [6314, 6547, 6298],
       [4181, 4381, 4186]])

In [ ]:
# Division
M1/M2

array([[0.3559322 , 0.44776119, 0.45588235],
       [0.61666667, 0.43478261, 0.64912281],
       [0.3968254 , 0.40740741, 0.39285714]])

In [ ]:
# Perform the dot product between two matrices of size (2x2)

# time -> 10:49

In [ ]:
M1 = np.array([[12,14],[10,8]])
M2 = np.array([[1,4],[20,16]])

In [ ]:
M1

array([[12, 14],
       [10,  8]])

In [ ]:
M2

array([[ 1,  4],
       [20, 16]])

In [ ]:
dot_product = np.dot(M1, M2)

In [ ]:
dot_product

array([[292, 272],
       [170, 168]])

In [ ]:
# Create a 3x3 random matrix and perform the transpose of it

# time -> 10:58

In [ ]:
M1 = np.random.randint(10,50, size=(3,3))
M1

array([[43, 39, 34],
       [35, 24, 11],
       [22, 18, 39]])

In [ ]:
trans_M1 = M1.T

In [ ]:
trans_M1

array([[43, 35, 22],
       [39, 24, 18],
       [34, 11, 39]])

In [ ]:
# Property 1 -> Transpose of a Transpose Matrix is the Original Matrix

# time -> 11:06

In [ ]:
A = np.array([[4,5,1],[3,8,4],[20,3,6]])
A

array([[ 4,  5,  1],
       [ 3,  8,  4],
       [20,  3,  6]])

In [ ]:
trans_A = A.T

In [ ]:
trans_A

array([[ 4,  3, 20],
       [ 5,  8,  3],
       [ 1,  4,  6]])

In [ ]:
Trans_trans_A = trans_A.T

In [ ]:
if (np.array_equal(A, Trans_trans_A)):
  print("Property 1 is Correct")
else:
  print("Wrong")

Property 1 is Correct


In [ ]:
# Property 2 -> Additive Property
# (A+B).T = A.T + B.T

In [ ]:
A

array([[ 4,  5,  1],
       [ 3,  8,  4],
       [20,  3,  6]])

In [ ]:
# Time -> 11:20

In [ ]:
A = np.array([[4,5,1],[3,8,4],[20,3,6]])
B = np.array([[12,14,5],[45,5,5],[9,8,3]])

In [ ]:
A

array([[ 4,  5,  1],
       [ 3,  8,  4],
       [20,  3,  6]])

In [ ]:
B

array([[12, 14,  5],
       [45,  5,  5],
       [ 9,  8,  3]])

In [ ]:
# L.H.S
lhs = (A+B).T
print(lhs)

# R.H.S
rhs = A.T + B.T
print(rhs)

if np.array_equal(lhs, rhs):
  print("Additive property is Correct")
else:
  print("Wrong")

[[16 48 29]
 [19 13 11]
 [ 6  9  9]]
[[16 48 29]
 [19 13 11]
 [ 6  9  9]]
Additive property is Correct


In [ ]:
# Property 3 -> Multiplicative Property
# (AxB).T = B.T x A.T

# time -> 11:34

In [ ]:
# L.H.S
lhs = np.dot(A,B).T
print(lhs)

# R.H.S
rhs = B.T.dot(A.T)
print(rhs)

if (np.array_equal(lhs, rhs)):
  print("Multiplicative Property is True")
else:
  print("Multiplicative Property is False")

[[282 432 429]
 [ 89 114 343]
 [ 48  67 133]]
[[282 432 429]
 [ 89 114 343]
 [ 48  67 133]]
Multiplicative Property is True


In [ ]:
# Determinant ->
# 3x3 matrix
# random

# time -> 12:08

In [ ]:
M1 = np.random.randint(10,50, size=(3,3))   # 10-> lower range, 50-> upper range
M1

array([[26, 45, 11],
       [10, 18, 38],
       [18, 26, 48]])

In [ ]:
np.linalg.det(M1)

np.float64(5251.999999999995)

In [ ]:
# Check if a matrix is invertible or a singular matrix
# Singular -> Determinant == 0
# Invertible -> Deteminant != 0

# time -> 12:20

In [ ]:
A = np.random.randint(1,10, size=(3,3))
A

array([[3, 7, 3],
       [1, 8, 3],
       [1, 6, 4]])

In [ ]:
detA = np.linalg.det(A)
if detA==0:
  print("A is Singular")
else:
  print("A is Invertible")

A is Invertible


In [ ]:
# Find the inverse of a Matrix
# A * A-1 = Indentity Matrix
# Prove it also

# time -> 12:34

In [ ]:
M = np.array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [ ]:
M_inv = np.linalg.inv(M)
M_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
result = np.dot(M, M_inv)

In [ ]:
result

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [ ]:
# np.allclose() -> Is a function in numpy to check if two matrix are equal or not...
# if there are some floating value or tiny errors then also it will consider both as same
if np.allclose(result, np.identity(2)):
  print("True")
else:
  print("False")

True


In [ ]:
# A = np.array([[1,2],[2,4]])
# B = np.array([[1,2],[5,6]])

# Calculate Rank of them

# time -> 12:46

In [ ]:
A = np.array([[1,2],[2,4]])
np.linalg.matrix_rank(A)

np.int64(1)

In [ ]:
B = np.array([[1,2],[5,6]])
np.linalg.matrix_rank(B)

np.int64(2)

In [ ]:
# A = np.array([[4,1],[2,3]])
# eigen values and eigen vectors...

# time -> 12:56

In [ ]:
A = np.array([[4,1],[2,3]])

In [ ]:
eig_val, eig_vec = np.linalg.eig(A)

In [ ]:
eig_val

array([5., 2.])

In [ ]:
eig_vec

array([[ 0.70710678, -0.4472136 ],
       [ 0.70710678,  0.89442719]])